eclipse-velocitas/cli

- .github/workflows/build-exe.yml
- .github/workflows/release.yml
- .vscode/settings.json
- NOTICE-3RD-PARTY-CONTENT.md
- package-lock.json
- package.json
- src/commands/init/index.ts
- src/modules/package.ts
- test/commands/init/init.test.ts
- test/commands/upgrade/upgrade.test.ts
Fixes proxy issues with the CLI and rate limiting issues by accepting GITHUB_API_TOKEN via env for all HTTP(S) requests.
> Fix proxy issues and API rate issues

- NOTICE-3RD-PARTY-CONTENT.md
- src/modules/setup.ts
Add fix for notice comment in tpl file
Signed-off-by: Dennis Meister <dennis.meister@bosch.com>
> Add fix for notice comment in tpl file

- NOTICE-3RD-PARTY-CONTENT.md
- package-lock.json
- package.json
- src/commands/init/index.ts
- src/commands/upgrade/index.ts
- src/modules/package.ts
- test/commands/init/init.test.ts
Add axios-retry for handling fallback url download of packages
Signed-off-by: Dennis Meister <dennis.meister@bosch.com>
> Add retry with fallback url for package download

- src/commands/package/index.ts
- src/modules/variables.ts
- test/unit/variables.test.ts
- test/utils/mockConfig.ts
Introduces support for defaults which turn required variables into optional variables.
> feat: Defaults for variables

- README.md
- src/modules/package.ts
- src/modules/project-config.ts
- test/unit/package.test.ts
Support for VELOCITAS_HOME environment variable to redirect the CLI data directory.
> feat: Support VELOCITAS_HOME env variable

- .github/workflows/check-licenses.yml
- NOTICE-3RD-PARTY-CONTENT.md
- src/modules/package.ts
Fix getting correct fallback url with axios retry
Signed-off-by: Dennis Meister <dennis.meister@bosch.com>
> Fix axios retry for correct fallback url

- NOTICE-3RD-PARTY-CONTENT.md
- src/modules/variables.ts
- test/unit/variables.test.ts
Fix a bug with exposed boolean variables with a default false value
> Fix bug with boolean default false variables

- .github/workflows/ci.yml
- NOTICE-3RD-PARTY-CONTENT.md
- package.json
- src/modules/exec.ts
- test/system-test/exec.stest.ts
- testbench/test-exec/.velocitas.json
- testbench/test-exec/app/AppManifest.json
Fixes a bug which occurs with executables with relative path not being found in the binary version of the CLI
> Fix exec bug

- src/commands/exec/index.ts
- src/commands/init/index.ts
- src/modules/component.ts
- src/modules/exec.ts
- src/modules/variables.ts
- test/commands/exec/exec.test.ts
- test/commands/init/init.test.ts
- test/utils/mockConfig.ts
Implements #58 . Post init hooks now are silent by default. Full logging can be enabled with the verbose flag.
> Feature: Silent post init hooks

- src/modules/package.ts
- src/modules/variables.ts
- test/unit/variables.test.ts
Introduce additional builtin variables which can be used for soft references to github workflow calls
> feat: Builtin variables

- src/commands/package/index.ts
- src/modules/component.ts
- test/commands/package/package.test.ts
- test/utils/mockConfig.ts
Allows exposed programs to have a description. Implements #92
> Feature: Add optional description to program specs

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
> Add ISSUE_TEMPLATE

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
> Update base image to v0.1

- src/commands/exec/index.ts
- src/commands/init/index.ts
- src/modules/package.ts
- src/modules/variables.ts
- test/system-test/exec.stest.ts
PR adds a new exposed environment variable which allows resolving of package paths.
> Feat: Add VELOCITAS_PACKAGE_DIR as exposed environment variable

- src/modules/exec.ts
This PR adds removal of event listeners to avoid possible memory leaks
> fix: remove event listeners to avoid memory leak

- .github/workflows/build-exe.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
Generate binaries for alpine linux.
> Generate alpine linux binaries

- src/modules/package.ts
Fix the used path for package installation check.
> fix: Correct package install path

- src/commands/cache/clear.ts
- src/commands/cache/get.ts
- src/commands/cache/set.ts
- src/commands/create/index.ts
- src/commands/exec/index.ts
- src/commands/init/index.ts
- src/commands/package/index.ts
- src/commands/sync/index.ts
- src/commands/upgrade/index.ts
- src/modules/project-config.ts
- test/commands/create/create.test.ts
- test/unit/project-config.test.ts
- test/unit/variables.test.ts
- testbench/test-create/vehicle-app-template/package-index.json
This PR adds adaptions to the create command
> fix: create command adaptions

- .devcontainer/devcontainer.json
- docs/features/VARIABLES.md
- src/commands/create/index.ts
- src/commands/exec/index.ts
- src/commands/init/index.ts
- src/commands/sync/index.ts
- src/modules/component.ts
- src/modules/exec.ts
- src/modules/project-config.ts
- src/modules/variables.ts
- test/commands/create/create.test.ts
- test/commands/sync/sync.test.ts
- test/unit/variables.test.ts
- test/utils/mockConfig.ts
Adds scope identifiers to variable definitions in toolchain components.
> feat: Variable scopes

- README.md
- package.json
- src/commands/component/add.ts
- src/commands/component/list.ts
- src/commands/component/remove.ts
- src/modules/component.ts
- src/modules/project-config.ts
- test/commands/component/component-add.test.ts
- test/commands/component/component-list.test.ts
- test/commands/component/component-remove.test.ts
- test/commands/component/component.test.ts
- test/helpers/simpleGit.ts
- test/unit/variables.test.ts
- test/utils/mockConfig.ts
Adds commands to interact with project components: list, add and remove.
> feat: component commands

- .github/workflows/ci.yml
- NOTICE-3RD-PARTY-CONTENT.md
This PR changes coverage github action due to external contributing/push to branch problem
> Change coverage action

- src/commands/create/index.ts
- test/system-test/init.stest.ts
- testbench/test-create/vehicle-app-template/package-index.json
- testbench/test-exec/app/AppManifest.json
- testbench/test-init/.velocitasLegacy.json
- testbench/test-init/.velocitasNew.json
- testbench/test-init/app/AppManifest.json
fixes the mandatory component selection on create command when using examples
> fix: mandatory component selection on create

- NOTICE-3RD-PARTY-CONTENT.md
- package-lock.json
- package.json
Replaces #308 
We could discuss if want to change dependabot updates here, either to only do security updates, or to do it a bit less frequent, like every month, as dependabot anyway does not know how to update our license file.
> Updating dependencies

- NOTICE-3RD-PARTY-CONTENT.md
- package-lock.json
- package.json
Long term we might also need to address #329 but that requires more work
Replaces the auto-generated PRs, this one include NOTICE update to make CI pass
> Dependency update
